---
title: Advanced R
format: 
  html:
    css: styles.css
    number-sections: true
  pdf:
    include-in-header:
      text: |
        \input{preamble.tex}
---
```{r}
library(rlang)
```


```{r}
y <- 10

f1 <- function(x = {y <- 1; 2}, y = 0) {
  c(x,y)
} 
f1(y = 30)
y
```


```{r}
f1 <- function(x = stop("This is an error!")) {
  stop <- function(...) Sys.time()
  print(x)
}
f1(x = stop("Error!"))
```
- Environments


```{r}
e1 <- env(
  a = FALSE,
  b = 1L,
  c = 2,
  d = "first"
)

env_print(e1)
names(e1)
ls(e1)
formals(ls)

env_print(current_env())
```

- Use `identical()` to check if two environments are the same


```{r}
identical(current_env(), e1)
identical(current_env(), global_env())
f1 <- function() {
  print(identical(current_env(), global_env()))
  print(identical(globalenv(), environment()))
  print(env_parents(current_env() , last = empty_env()))
}
f1()
```

- Checking which environment is updated by `<<-`


```{r}
f1 <- function() {
  f2 <- function() {
    a <<- 21
  }
  f2()
  env_print(current_env())
  env_print(global_env())
}
f1()

```

-- *Functionals* using `purrr`


```{r}
library(purrr)
library(tibble)
```


```{r}
data.frame(map2(1:3, 20, `+`)) 
```

```{r}
vals <- mtcars |> split(mtcars$cyl)
vals |>
  map(~ lm(mpg ~ wt, data = .x)) |> 
  map(summary) |>
  map_dbl("adj.r.squared")
  # map_dbl(2)
```


```{r}
df <- data.frame(
x = 1:10,
y = 11:20
)
df
pwalk(df, \(...) print(paste(...)))

```

