---
title: R 4 DS, ch15, Regex
format: html
---

```{r}
#| message: false
library(tidyverse)
library(babynames)
```


```{r}
df <- tribble(
  ~name, ~lastname, ~location, ~score,
  "John", "Doe", "USA", 20,
  "Dave", "Logan", "UK", 20,
  "Sam", "Wood", "UK", 40
)

df |>
  select(matches("^l"))

df |>
  filter(str_detect(name, "[nm]$")) |>
  mutate(name = str_to_lower(name))
```
* separating values

```{r}
df <- tribble(
  ~str,
  "<Sheryl>-F_34",
  "<Kisha>-F_45", 
  "<Brandon>-N_33",
  "<Sharon>-F_38", 
  "<Penny>-F_58",
  "<Justin>-M_41", 
  "<Patricia>-F_84", 
)

df |>
  separate_wider_regex(
    str,
    patterns = c("<",
      name = "[A-Za-z]+",
      ">-",
      gender = "\\w",
      "_",
      age = "\\d{2}"
    )
  )
```
* does mutate using non-summarise function use grouped values


```{r}
df |>
  group_by(location) |>
  mutate(sc_ratio = score / sum(score)) |>
  count(score)
```
* would `geom_bar` work with a non-factor field


```{r}
df <- tribble(
  ~pop, ~city_type,
  10,"A",
  20,"B",
  11,"A",
  13,"A",
  14,"B",
)

df |>
  ggplot(aes(x = city_type, y = after_stat(prop), group = 1)) +
  geom_bar()

```

